apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-core-services
  namespace: argocd
spec:
  destination:
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster-services
    repoURL: https://bitbucket.org/umsa-dev/argocd-gitops.git
    targetRevision: HEAD
    directory:
      recurse: false
  project: core-services
  # syncPolicy: {}
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true